/**
 * Sidebar navigation, declared per role.
 *
 * The shape and wording of the nav are a design decision (docs/design-brief.md
 * §3), so they live in a config object rather than being inferred from
 * permissions — labels and grouping remain explicit while route access stays
 * centralized in the role matrix.
 *
 * Access, though, is not a design decision. Everything here is filtered
 * through `canAccessRoute` before it renders, so the role matrix stays the one
 * thing that decides what a role can reach. A nav item the matrix forbids
 * simply never appears, and `nav-config.test.ts` fails if one is ever added.
 */

import type { Href } from 'expo-router';
import {
  Boxes,
  Building2,
  LayoutDashboard,
  Package,
  ReceiptText,
  ShoppingCart,
  Sparkles,
  Store,
  Tag,
  TrendingUp,
  TriangleAlert,
  Users,
  type LucideIcon,
} from 'lucide-react-native';

import { canAccessRoute, type Role } from '@/lib/auth/permissions';

/**
 * The string half of Href: route paths, minus the object form, so these stay
 * comparable and usable as React keys.
 *
 * app.json sets `experiments.typedRoutes`, which would narrow this to the
 * generated route literals and reject a typo at build time — but only once
 * `.expo/types` has been generated by running the dev server. On a clean
 * checkout it resolves to plain `string`, so do not rely on it to catch a bad
 * path. The nav-config tests check every href against the route rules instead,
 * which does not depend on codegen.
 */
export type RoutePath = Extract<Href, string>;

export type NavItem = {
  /** Absolute path, matched against the current route to set the active state. */
  href: RoutePath;
  label: string;
  icon: LucideIcon;
  /**
   * Matches child routes too. `/inventory` would otherwise stay highlighted on
   * `/inventory/low-stock`, which has its own item.
   */
  exact?: boolean;
};

export type NavSection = {
  /** Rendered as a small caption above the group. Cashier has none. */
  title?: string;
  items: NavItem[];
};

const NAV: Record<Role, NavSection[]> = {
  OWNER: [
    {
      title: 'Dashboard',
      items: [
        { href: '/dashboard', label: 'Dashboard', icon: LayoutDashboard, exact: true },
        { href: '/analytics', label: 'Analitik', icon: TrendingUp },
        { href: '/ai-insights', label: 'AI Insight', icon: Sparkles },
      ],
    },
    {
      title: 'Bisnis',
      items: [
        { href: '/outlets', label: 'Outlet', icon: Store },
        { href: '/users', label: 'Staf', icon: Users },
        { href: '/merchant', label: 'Merchant', icon: Building2 },
      ],
    },
    {
      title: 'Katalog',
      items: [
        { href: '/products', label: 'Produk', icon: Package },
        { href: '/categories', label: 'Kategori', icon: Tag },
        // Read-only for the Owner, per the matrix. The brief's §3 Owner nav
        // omits this, but CLAUDE.md's route list carries it.
        { href: '/inventory', label: 'Stok', icon: Boxes, exact: true },
      ],
    },
    {
      title: 'Riwayat',
      items: [{ href: '/transactions', label: 'Transaksi', icon: ReceiptText }],
    },
  ],

  ADMIN: [
    {
      title: 'Operasional',
      items: [
        { href: '/inventory', label: 'Inventori', icon: Boxes, exact: true },
        { href: '/inventory/low-stock', label: 'Stok Menipis', icon: TriangleAlert },
      ],
    },
    {
      title: 'Katalog',
      items: [
        { href: '/products', label: 'Produk', icon: Package },
        { href: '/categories', label: 'Kategori', icon: Tag },
      ],
    },
  ],

  // No section titles: two items do not need grouping.
  CASHIER: [
    {
      items: [
        { href: '/pos', label: 'Kasir', icon: ShoppingCart },
        { href: '/transactions', label: 'Riwayat', icon: ReceiptText },
      ],
    },
  ],
};

/** The role's nav, with anything the matrix forbids removed. */
export function navFor(role: Role): NavSection[] {
  return NAV[role]
    .map((section) => ({
      ...section,
      items: section.items.filter((item) => canAccessRoute(role, item.href)),
    }))
    .filter((section) => section.items.length > 0);
}

/** Flat list, in sidebar order. The bottom tab bar and icon rail use this. */
export function navItemsFor(role: Role): NavItem[] {
  return navFor(role).flatMap((section) => section.items);
}

/**
 * Which item owns the current route.
 *
 * Longest match wins, so `/inventory/low-stock` highlights its own item rather
 * than the `/inventory` one above it.
 */
export function activeHref(items: NavItem[], pathname: string): RoutePath | null {
  const matches = items.filter((item) =>
    item.exact
      ? pathname === item.href
      : pathname === item.href || pathname.startsWith(`${item.href}/`)
  );

  return matches.sort((a, b) => b.href.length - a.href.length)[0]?.href ?? null;
}

export { NAV as NAV_CONFIG };
